from django.db import models as m
from device import models

# Create your models here.
# class Device(m.Model):
#     d_id = m.CharField(max_length=50)
#     d_info = m.CharField(max_length=50)
#     type_id = m.CharField(max_length=50)
#     status_id = m.CharField(max_length=2)
#     period_mins = m.CharField(max_length=2)
        
#     def __str__(self):
#         return 'd_id:%s,d_info:%s,type_id:%s,status_id:%s,period_mins:%s' 
#             % (self.d_id, self.d_info, self.type_id, self.status_id, self.period_mins)

#water_quality_log table     
class Water_param(m.Model):
    device = m.ForeignKey(models.Device,blank=True,null=True)
    ph = m.CharField(max_length=20,blank=True,null=True)
    turbidity = m.CharField(max_length=20,blank=True,null=True)
    rc = m.CharField(max_length=20,blank=True,null=True)
    d_oxygen = m.CharField(max_length=20,blank=True,null=True)
    conductivity = m.CharField(max_length=20,blank=True,null=True)
    fluoride = m.CharField(max_length=20,blank=True,null=True)
    temperature = m.CharField(max_length=20,blank=True,null=True)
    d_hcl = m.CharField(max_length=20,blank=True,null=True)
    d_na2co3 = m.CharField(max_length=20,blank=True,null=True)
    d_h2so4 = m.CharField(max_length=20,blank=True,null=True)
    d_naoh = m.CharField(max_length=20,blank=True,null=True)
    orp = m.CharField(max_length=20,blank=True,null=True)
    is_ok = m.IntegerField()
    send_time = m.DateTimeField(auto_now_add=True)

    def __str__(self):
        return 'device_id:%s,ph:%s,is_ok:%d' % (self.device_id, self.ph, self.is_ok)


class Water_param_corp_week(m.Model):
    corp = m.ForeignKey(models.Watercorp)
    ph = m.CharField(max_length=20,blank=True,null=True)
    turbidity = m.CharField(max_length=20,blank=True,null=True)
    rc = m.CharField(max_length=20,blank=True,null=True)
    d_oxygen = m.CharField(max_length=20,blank=True,null=True)
    conductivity = m.CharField(max_length=20,blank=True,null=True)
    fluoride = m.CharField(max_length=20,blank=True,null=True)
    temperature = m.CharField(max_length=20,blank=True,null=True)
    d_hcl = m.CharField(max_length=20,blank=True,null=True)
    d_na2co3 = m.CharField(max_length=20,blank=True,null=True)
    d_h2so4 = m.CharField(max_length=20,blank=True,null=True)
    d_naoh = m.CharField(max_length=20,blank=True,null=True)
    orp = m.CharField(max_length=20,blank=True,null=True)
    is_ph_ok = m.IntegerField()
    is_turbidity_ok = m.IntegerField()
    is_rc_ok = m.IntegerField()
    is_do_ok = m.IntegerField()
    is_conductivity_ok = m.IntegerField()
    is_fluoride_ok = m.IntegerField()
    is_temperature_ok = m.IntegerField()
    is_hcl_ok = m.IntegerField()
    is_na2co3_ok = m.IntegerField()
    is_h2so4_ok = m.IntegerField()
    is_naoh_ok = m.IntegerField()
    is_orp_ok = m.IntegerField()
    is_ok = m.IntegerField()
    week_info = m.CharField(max_length=200,)#20140901-20140908,1st
    log_time = m.DateTimeField(auto_now_add=True)

class Water_param_corp_month(m.Model):
    corp = m.ForeignKey(models.Watercorp)
    ph = m.CharField(max_length=20,blank=True,null=True)
    turbidity = m.CharField(max_length=20,blank=True,null=True)
    rc = m.CharField(max_length=20,blank=True,null=True)
    d_oxygen = m.CharField(max_length=20,blank=True,null=True)
    conductivity = m.CharField(max_length=20,blank=True,null=True)
    fluoride = m.CharField(max_length=20,blank=True,null=True)
    temperature = m.CharField(max_length=20,blank=True,null=True)
    d_hcl = m.CharField(max_length=20,blank=True,null=True)
    d_na2co3 = m.CharField(max_length=20,blank=True,null=True)
    d_h2so4 = m.CharField(max_length=20,blank=True,null=True)
    d_naoh = m.CharField(max_length=20,blank=True,null=True)
    orp = m.CharField(max_length=20,blank=True,null=True)
    is_ph_ok = m.IntegerField()
    is_turbidity_ok = m.IntegerField()
    is_rc_ok = m.IntegerField()
    is_do_ok = m.IntegerField()
    is_conductivity_ok = m.IntegerField()
    is_fluoride_ok = m.IntegerField()
    is_temperature_ok = m.IntegerField()
    is_hcl_ok = m.IntegerField()
    is_na2co3_ok = m.IntegerField()
    is_h2so4_ok = m.IntegerField()
    is_naoh_ok = m.IntegerField()
    is_orp_ok = m.IntegerField()
    is_ok = m.IntegerField()
    month_info = m.CharField(max_length=200,)#20140901-20140908,1st
    log_time = m.DateTimeField(auto_now_add=True)

class Water_param_subcorp_week(m.Model):
    corp = m.ForeignKey(models.Watercorp)
    ph = m.CharField(max_length=20,blank=True,null=True)
    turbidity = m.CharField(max_length=20,blank=True,null=True)
    rc = m.CharField(max_length=20,blank=True,null=True)
    d_oxygen = m.CharField(max_length=20,blank=True,null=True)
    conductivity = m.CharField(max_length=20,blank=True,null=True)
    fluoride = m.CharField(max_length=20,blank=True,null=True)
    temperature = m.CharField(max_length=20,blank=True,null=True)
    d_hcl = m.CharField(max_length=20,blank=True,null=True)
    d_na2co3 = m.CharField(max_length=20,blank=True,null=True)
    d_h2so4 = m.CharField(max_length=20,blank=True,null=True)
    d_naoh = m.CharField(max_length=20,blank=True,null=True)
    orp = m.CharField(max_length=20,blank=True,null=True)
    is_ph_ok = m.IntegerField()
    is_turbidity_ok = m.IntegerField()
    is_rc_ok = m.IntegerField()
    is_do_ok = m.IntegerField()
    is_conductivity_ok = m.IntegerField()
    is_fluoride_ok = m.IntegerField()
    is_temperature_ok = m.IntegerField()
    is_hcl_ok = m.IntegerField()
    is_na2co3_ok = m.IntegerField()
    is_h2so4_ok = m.IntegerField()
    is_naoh_ok = m.IntegerField()
    is_orp_ok = m.IntegerField()
    is_ok = m.IntegerField()
    week_info = m.CharField(max_length=200,)#20140901-20140908,1st
    log_time = m.DateTimeField(auto_now_add=True)

class Water_param_subcorp_month(m.Model):
    corp = m.ForeignKey(models.Watercorp)
    ph = m.CharField(max_length=20,blank=True,null=True)
    turbidity = m.CharField(max_length=20,blank=True,null=True)
    rc = m.CharField(max_length=20,blank=True,null=True)
    d_oxygen = m.CharField(max_length=20,blank=True,null=True)
    conductivity = m.CharField(max_length=20,blank=True,null=True)
    fluoride = m.CharField(max_length=20,blank=True,null=True)
    temperature = m.CharField(max_length=20,blank=True,null=True)
    d_hcl = m.CharField(max_length=20,blank=True,null=True)
    d_na2co3 = m.CharField(max_length=20,blank=True,null=True)
    d_h2so4 = m.CharField(max_length=20,blank=True,null=True)
    d_naoh = m.CharField(max_length=20,blank=True,null=True)
    orp = m.CharField(max_length=20,blank=True,null=True)
    is_ph_ok = m.IntegerField()
    is_turbidity_ok = m.IntegerField()
    is_rc_ok = m.IntegerField()
    is_do_ok = m.IntegerField()
    is_conductivity_ok = m.IntegerField()
    is_fluoride_ok = m.IntegerField()
    is_temperature_ok = m.IntegerField()
    is_hcl_ok = m.IntegerField()
    is_na2co3_ok = m.IntegerField()
    is_h2so4_ok = m.IntegerField()
    is_naoh_ok = m.IntegerField()
    is_orp_ok = m.IntegerField()
    is_ok = m.IntegerField()
    month_info = m.CharField(max_length=200,)#20140901-20140908,1st
    log_time = m.DateTimeField(auto_now_add=True)